# x = int(input('Введите число 1 '))
# y = int(input('Введите число 2 '))
# z = int(input('Введите число 3 '))
# print(x*y*z)
# print(x+y+z)
x = int(input('Введите число 1 '))
y = int(input('Введите число 2 '))
z = int(input('Введите число 3 '))
print(x-y-z)